"""empty message

Revision ID: 5c71860e78cd
Revises: 2307c2f84904
Create Date: 2026-01-21 11:53:18.636904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c71860e78cd'
down_revision = '2307c2f84904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_follower_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_receiver_id_fkey', 'post', ['receiver_id'], ['id'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_follower_id_fkey', 'post', ['follower_id'], ['id'])

    # ### end Alembic commands ###
